export const universityData = {
  UK: [
    "Ulster University London",
    "Northumbria University London",
    "University of Greenwich",
    "London Metropolitan University",
    "University of Roehampton London",
    "University of South Wales",
    "University of Sunderland London",
    "London South Bank University",
    "University of East London",
  ],
  Canada: [
    "Wilfrid Laurier University",
    "University of Regina",
    "University of Manitoba",
    "University Canada West",
    "Southern Alberta Institute of Technology (SAIT)",
    "Niagara College, Toronto",
    "Mount Allison University",
    "MacEwan University",
    "Lethbridge College",
    "Laurentian University",
    "Fanshawe College",
    "Capilano University",
    "British Columbia Institute of Technology (BCIT)",
    "Brescia University College – Western University",
    "Algoma University",
    "Acsenda School of Management",
  ],
  Australia: [
    "University of Canberra",
    "Torrens University Australia",
    "Charles Darwin University",
    "Charles Sturt University",
    "University of Wollongong Australia (UOW)",
    "Southern Cross University (SCU)",
    "CQ University",
    "Edith Cowan University",
    "Deakin University",
  ],
  "New Zealand": [
    "Victoria University of Wellington",
    "University of Otago",
    "The University of Waikato",
    "Southern Institute of Technology (SIT)",
    "Massey University (via Kaplan)",
    "Manukau Institute of Technology",
    "Auckland Institute of Studies",
  ],
  USA: [
    "University of West Florida (UWF)",
    "University of Maryland, Baltimore County (UMBC)",
    "Auburn University Alabama",
    "The University of Alabama (UA)",
    "Murray State University",
    "Kent State University",
  ],
  Asia: {
    Thailand: ["Shinawatra University"],
    Malaysia: [
      "INTI University",
      "City University",
      "University of Cyberjaya",
      "Multimedia University",
      "Asia Pacific University",
      "SEGI University",
    ],
    Singapore: ["Singapore University of Technology and Design"],
  },
  Europe: {
    Hungary: [
      "University of Debrecen",
      "Budapest Metropolitan University",
      "Wekerley Business School",
    ],
    Malta: ["GBS Malta", "Idea College", "Ascencia Malta"],
    Denmark: [
      "Copenhagen Business College",
      "International Business Academy",
      "Technical University of Denmark",
    ],
    Ireland: ["Dublin Business School", "IBAT College", "Griffith College"],
  },
};
